version: '3'
services:
  mini_server:
    image: mini_server:0.1
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - 80:8080
    networks:
      - mynetwork
    depends_on:
      - mini_server

networks:
  mynetwork:
    driver: bridge